# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12ed82f5b4646d60052fc013eb72306e666593be0f1aee053635bf5e1ec94bb2e0af8fdeced6f57cc9dd01b19d3d86b85c570c329dc1f1a49d5fba458868607a

test:
  secret_key_base: 3a784103d0b4e40f491793b4bfb3b1be3a4c759509b0dd1c38b76b0f1c2ad987c48be49e09dc64e987822258d97b520854334275847771dc90aba1a6fd66416d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
